spring:
  data:
    redis:
      host: ${PRESENCE_REDIS_HOST:redis}
      port: ${PRESENCE_REDIS_PORT:6379}
      password: ${PRESENCE_REDIS_PASSWORD:}

identity:
  service:
    base-url: ${IDENTITY_SERVICE_BASE_URL:http://identity-service:8081}
