server:
  port: ${MESSAGE_STORAGE_SERVICE_PORT:8084}

spring:
  datasource:
    url: ${MESSAGE_STORAGE_DB_URL:jdbc:postgresql://localhost:5432/message_storage_service}
    username: ${MESSAGE_STORAGE_DB_USERNAME:postgres}
    password: ${MESSAGE_STORAGE_DB_PASSWORD:postgres}
  flyway:
    enabled: ${MESSAGE_STORAGE_FLYWAY_ENABLED:true}
    url: ${MESSAGE_STORAGE_FLYWAY_URL:${MESSAGE_STORAGE_DB_URL:jdbc:postgresql://localhost:5432/message_storage_service}}
    user: ${MESSAGE_STORAGE_FLYWAY_USERNAME:${MESSAGE_STORAGE_DB_USERNAME:postgres}}
    password: ${MESSAGE_STORAGE_FLYWAY_PASSWORD:${MESSAGE_STORAGE_DB_PASSWORD:postgres}}
  rabbitmq:
    host: ${MESSAGE_STORAGE_RABBITMQ_HOST:localhost}
    port: ${MESSAGE_STORAGE_RABBITMQ_PORT:5672}
    username: ${MESSAGE_STORAGE_RABBITMQ_USERNAME:guest}
    password: ${MESSAGE_STORAGE_RABBITMQ_PASSWORD:guest}
  cassandra:
    contact-points: ${MESSAGE_STORAGE_CASSANDRA_CONTACT_POINTS:localhost}
    port: ${MESSAGE_STORAGE_CASSANDRA_PORT:9042}
    keyspace-name: ${MESSAGE_STORAGE_CASSANDRA_KEYSPACE:connect_chat}
    local-datacenter: ${MESSAGE_STORAGE_CASSANDRA_DATACENTER:datacenter1}
    schema-action: ${MESSAGE_STORAGE_CASSANDRA_SCHEMA_ACTION:NONE}
