server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/group_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    url: ${FLYWAY_URL:${DB_URL:jdbc:postgresql://localhost:5432/group_service}}
    user: ${FLYWAY_USERNAME:${DB_USERNAME:postgres}}
    password: ${FLYWAY_PASSWORD:${DB_PASSWORD:postgres}}
