spring:
  application:
    name: group-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

identity:
  service:
    base-url: ${IDENTITY_SERVICE_BASE_URL:http://localhost:8081}
